### ISSUE TITLE
inner vs outer scope convention

### ISSUE THREAD

**Issue by fommil** [TomasMikula/pascal#2]
I don't know if this sounds crazy, or if it's even possible, but I find that the biggest amount of boilerplate I see in kind-projector comes from the lambda syntax. e.g.

```scala
    def states[S1, S2]: λ[α => State[S1, State[S2, α]]] ~> State[(S1, S2), ?] = ...
```

I wonder if there could perhaps be an opportunity for further syntax sugar in pascal to have some other symbol, maybe `??`, that binds to the most outer type, or a pair of enclosing brackets `( ... )` provided by the user. The above would then be

```scala
    def states[S1, S2]: State[S1, State[S2, ??]] ~> State[(S1, S2), ?] = ...
```

too much magic?

and we could even use it to clarify ambiguous `?`, e.g.

```scala
    def states[S1, S2]: (State[S1, State[S2, ??]]) ~> (State[(S1, S2), ??]) = ...
```

**Comment by TomasMikula** [comment]
The idea of outermost scope seems sketchy: the meaning of a type expression would depend on context. That it is error prone is illustrated by the fact that you made a mistake already in your example:

```scala
State[S1, State[S2, ??]] ~> State[(S1, S2), ?]
```

would be

```scala
λ[α => State[S1, State[S2, α]] ~> State[(S1, S2), ?]]
```

which is not what you meant (and left-hand side of `~>` doesn't even have the correct kind here).

However, there is a recent proposal for more concise syntax for binding at outer levels at https://github.com/non/kind-projector/issues/69. I'm open to a good argument, but haven't been convinced yet.

**Comment by fommil** [comment]
I had thought of this counterexample, which is why I suggested the brackets. But it might be too easy to fall into the trap... and far too complicated to actually implement the logic. I didn't know about the kind-projector ticket, I'll move the discussion there!

**Comment by TomasMikula** [comment]
AFAIK, extra brackets are not part of the AST.
